### ISSUE TITLE
Current State = Loading...

### ISSUE THREAD

**Issue by mmurushkin** [eyesulu/DENKOVY_RELAY#1]
Current state of the relay is not shown as expected. 
![Screenshot from 2023-07-10 14-52-13](https://github.com/eyesulu/DENKOVY_RELAY/assets/122713429/b185c6c4-22f9-4bd3-8aa9-d552dc058ac5)

**Comment by mmurushkin** [comment]
Exception on /get_state [GET]
Traceback (most recent call last):
  File "/home/siner/radioconda/lib/python3.10/site-packages/pysnmp/carrier/asyncore/dispatch.py", line 45, in runDispatcher
    loop(timeout or self.getTimerResolution(),
  File "/home/siner/radioconda/lib/python3.10/asyncore.py", line 214, in loop
    poll_fun(timeout, map)
  File "/home/siner/radioconda/lib/python3.10/asyncore.py", line 195, in poll2
    readwrite(obj, flags)
  File "/home/siner/radioconda/lib/python3.10/asyncore.py", line 130, in readwrite
    obj.handle_error()
  File "/home/siner/radioconda/lib/python3.10/asyncore.py", line 115, in readwrite
    obj.handle_read_event()
  File "/home/siner/radioconda/lib/python3.10/asyncore.py", line 427, in handle_read_event
    self.handle_read()
  File "/home/siner/radioconda/lib/python3.10/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
    self._cbFun(self, transportAddress, incomingMessage)
  File "/home/siner/radioconda/lib/python3.10/site-packages/pysnmp/carrier/base.py", line 84, in _cbFun
    self.__recvCallables[recvId](
  File "/home/siner/radioconda/lib/python3.10/site-packages/pysnmp/entity/engine.py", line 151, in __receiveMessageCbFun
    self.msgAndPduDsp.receiveMessage(
  File "/home/siner/radioconda/lib/python3.10/site-packages/pysnmp/proto/rfc3412.py", line 291, in receiveMessage
    msgVersion = verdec.decodeMessageVersion(wholeMsg)
  File "/home/siner/radioconda/lib/python3.10/site-packages/pysnmp/proto/api/verdec.py", line 15, in decodeMessageVersion
    seq, wholeMsg = decoder.decode(
  File "/home/siner/radioconda/lib/python3.10/site-packages/pyasn1/codec/ber/decoder.py", line 2003, in __call__
    for asn1Object in streamingDecoder:
  File "/home/siner/radioconda/lib/python3.10/site-packages/pyasn1/codec/ber/decoder.py", line 1918, in __iter__
    for asn1Object in self._singleItemDecoder(
  File "/home/siner/radioconda/lib/python3.10/site-packages/pyasn1/codec/ber/decoder.py", line 1778, in __call__
    for value in concreteDecoder.valueDecoder(
  File "/home/siner/radioconda/lib/python3.10/site-packages/pyasn1/codec/ber/decoder.py", line 654, in valueDecoder
    for chunk in substrateFun(asn1Object, substrate, length, options):
TypeError: decodeMessageVersion.<locals>.<lambda>() takes 3 positional arguments but 4 were given

**Comment by mmurushkin** [comment]
[https://github.com/etingof/pysnmp/issues/440]
pyasn1 version was 0.5.0, after downgrade to 0.4.8, the issue was fixed,

pip3 install --upgrade pyasn1==0.4.8

**Comment by mmurushkin** [comment]
Please add information about this bug/requirement to Readme.md

**Comment by eyesulu** [comment]
Added the information about versions of libraries in use
